#ifndef _USER_DEFINE_H_
#define _USER_DEFINE_H_

/* DMA definition */
#define U4_RX_DMA_UNIT (CM_DMA1)
#define U2_RX_DMA_UNIT (CM_DMA1)

#define U4_RX_DMA_CH (DMA_CH0)
#define U2_RX_DMA_CH (DMA_CH1)

#define U4_RX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA1, ENABLE))
#define U2_RX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA1, ENABLE))

#define U4_RX_DMA_TRIG_SEL (AOS_DMA1_0)
#define U2_RX_DMA_TRIG_SEL (AOS_DMA1_1)

#define U4_RX_DMA_TRIG_EVT_SRC (EVT_SRC_USART4_RI)
#define U2_RX_DMA_TRIG_EVT_SRC (EVT_SRC_USART2_RI)

#define U4_RX_DMA_RECONF_TRIG_SEL (AOS_DMA_RC)
#define U2_RX_DMA_RECONF_TRIG_SEL (AOS_DMA_RC)

#define U4_RX_DMA_RECONF_TRIG_EVT_SRC (EVT_SRC_AOS_STRG)
#define U2_RX_DMA_RECONF_TRIG_EVT_SRC (EVT_SRC_AOS_STRG)

#define U4_RX_DMA_TC_INT (DMA_INT_TC_CH0)
#define U2_RX_DMA_TC_INT (DMA_INT_TC_CH1)

#define U4_RX_DMA_TC_FLAG (DMA_FLAG_TC_CH0)
#define U2_RX_DMA_TC_FLAG (DMA_FLAG_TC_CH1)

#define U4_RX_DMA_TC_IRQn (INT000_IRQn)
#define U2_RX_DMA_TC_IRQn (INT005_IRQn)

#define U4_RX_DMA_TC_INT_SRC (INT_SRC_DMA1_TC0)
#define U2_RX_DMA_TC_INT_SRC (INT_SRC_DMA1_TC1)

#define U4_TX_DMA_UNIT (CM_DMA2)
#define U2_TX_DMA_UNIT (CM_DMA2)

#define U4_TX_DMA_CH (DMA_CH0)
#define U2_TX_DMA_CH (DMA_CH1)

#define U4_TX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA2, ENABLE))
#define U2_TX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA2, ENABLE))

#define U4_TX_DMA_TRIG_SEL (AOS_DMA2_0)
#define U2_TX_DMA_TRIG_SEL (AOS_DMA2_1)

#define U4_TX_DMA_TRIG_EVT_SRC (EVT_SRC_USART4_TI)
#define U2_TX_DMA_TRIG_EVT_SRC (EVT_SRC_USART2_TI)

#define U4_TX_DMA_TC_INT (DMA_INT_TC_CH0)
#define U2_TX_DMA_TC_INT (DMA_INT_TC_CH1)

#define U4_TX_DMA_TC_FLAG (DMA_FLAG_TC_CH0)
#define U2_TX_DMA_TC_FLAG (DMA_FLAG_TC_CH1)

#define U4_TX_DMA_TC_IRQn (INT001_IRQn)
#define U2_TX_DMA_TC_IRQn (INT006_IRQn)

#define U4_TX_DMA_TC_INT_SRC (INT_SRC_DMA2_TC0)
#define U2_TX_DMA_TC_INT_SRC (INT_SRC_DMA2_TC1)

/* Timer0 unit & channel definition */
#define U4_TMR0_UNIT (CM_TMR0_2)
// U2对应的是TMR0_1 CHB，U4对应的是TMR0_2 CHB，注意区分
#define U2_TMR0_UNIT (CM_TMR0_1)

#define U4_TMR0_CH (TMR0_CH_B)
#define U2_TMR0_CH (TMR0_CH_B)

#define U4_TMR0_FCG_ENABLE() (FCG_Fcg2PeriphClockCmd(FCG2_PERIPH_TMR0_2, ENABLE))
#define U2_TMR0_FCG_ENABLE() (FCG_Fcg2PeriphClockCmd(FCG2_PERIPH_TMR0_1, ENABLE))

/* USART RX/TX pin definition */
#define U4_USART_RX_PORT (GPIO_PORT_B) /* PB9: USART4_RX */
#define U2_USART_RX_PORT (GPIO_PORT_A) /* PA2: USART2_RX*/

#define U4_USART_RX_PIN (GPIO_PIN_09)
#define U2_USART_RX_PIN (GPIO_PIN_02)

#define U4_USART_RX_GPIO_FUNC (GPIO_FUNC_37)
#define U2_USART_RX_GPIO_FUNC (GPIO_FUNC_37)

#define U4_USART_TX_PORT (GPIO_PORT_B) /* PB8: USART4_TX */
#define U2_USART_TX_PORT (GPIO_PORT_A) /* PA3: USART2_TX */

#define U4_USART_TX_PIN (GPIO_PIN_08)
#define U2_USART_TX_PIN (GPIO_PIN_03)

#define U4_USART_TX_GPIO_FUNC (GPIO_FUNC_36)
#define U2_USART_TX_GPIO_FUNC (GPIO_FUNC_36)

/* USART unit definition */
#define U4_USART_UNIT (CM_USART4)
#define U2_USART_UNIT (CM_USART2)

#define U4_USART_FCG_ENABLE() (FCG_Fcg1PeriphClockCmd(FCG1_PERIPH_USART4, ENABLE))
#define U2_USART_FCG_ENABLE() (FCG_Fcg1PeriphClockCmd(FCG1_PERIPH_USART2, ENABLE))

/* USART baudrate definition */
#define U4_USART_BAUDRATE (115200UL)
#define U2_USART_BAUDRATE (921600UL)

/* USART timeout bits definition */
#define U4_USART_TIMEOUT_BITS (2000U)
#define U2_USART_TIMEOUT_BITS (2000U)

/* USART interrupt definition */
#define U4_USART_TX_CPLT_IRQn (INT002_IRQn)
#define U2_USART_TX_CPLT_IRQn (INT007_IRQn)

#define U4_USART_TX_CPLT_INT_SRC (INT_SRC_USART4_TCI)
#define U2_USART_TX_CPLT_INT_SRC (INT_SRC_USART2_TCI)

#define U4_USART_RX_ERR_IRQn (INT003_IRQn)
#define U2_USART_RX_ERR_IRQn (INT008_IRQn)

#define U4_USART_RX_ERR_INT_SRC (INT_SRC_USART4_EI)
#define U2_USART_RX_ERR_INT_SRC (INT_SRC_USART2_EI)

#define U4_USART_RX_TIMEOUT_IRQn (INT004_IRQn)
#define U2_USART_RX_TIMEOUT_IRQn (INT009_IRQn)

#define U4_USART_RX_TIMEOUT_INT_SRC (INT_SRC_USART4_RTO)
#define U2_USART_RX_TIMEOUT_INT_SRC (INT_SRC_USART2_RTO)

/* Application frame length max definition */
#define APP_FRAME_LEN_MAX (500U)

#define ADC_UNIT (CM_ADC1)

#define ADC_PERIPH_CLK (FCG3_PERIPH_ADC1)
/* --- single channel --- */
#define ADC_CHX (ADC_CH9)
#define ADC_CHX_PORT (GPIO_PORT_B)
#define ADC_CHX_PIN (GPIO_PIN_01)
#define ADC_SEQ (ADC_SEQ_A)

/* DR for this channel */
#define ADC_DR_ADDR ((uint32_t)&ADC_UNIT->DR9) // CH9 -> DR9（按你示例习惯）

/* ring buffer length */
#define ADC_BUF_LEN (10U) // 10个样本的缓冲区
#define ADC_DMA_SRC_ADDR (ADC_DR_ADDR)
#define ADC_DMA_TRANS_CNT (0)  // always
#define ADC_DMA_BLOCK_SIZE (1U) // ★每次触发搬1个
#define ADC_DMA_DATA_WIDTH (DMA_DATAWIDTH_16BIT)
#define ADC_DMA_DEST_ADDR ((uint32_t)(&m_au16AdcBuf[0U]))
#define ADC_DMA_TRIG_EVT (EVT_SRC_ADC1_EOCA)

#define ADC_DMA_UNIT (CM_DMA1)
#define ADC_DMA_PERIPH_CLK (FCG0_PERIPH_DMA1)
#define ADC_DMA_CH (DMA_CH2)
#define ADC_DMA_AOS_TRIG_SEL (AOS_DMA1_2)

#define ADC_DMA_INT_TYPE (DMA_INT_BTC_CH2)
#define ADC_DMA_INT_SRC (INT_SRC_DMA1_BTC2)
#define ADC_DMA_INT_IRQn (INT038_IRQn)

#define ADC_DMA_INT_PRIO (DDL_IRQ_PRIO_03)
#define ADC_DMA_INT_FLAG (DMA_FLAG_BTC_CH2)

#define INPUT_CH_NUMBER 16

#define ADC_CHANNEL_NUMBER 16

#define MAX_CHANNELS INPUT_CH_NUMBER

#define ADC_BUFFER_SIZE ADC_BUF_LEN // 80 // 10 // Define the size of the ADC buffer

#define TOTAL_POINTS (INPUT_CH_NUMBER * ADC_CHANNEL_NUMBER) // 256

// 点数量加上帧尾, 加左右两边帧头
// 16个字节的MEMS数据
#define OLD_FRAME_LEN (TOTAL_POINTS + 8 + 4 + 16)

#define USE_PRESS 0

#endif /* _USER_DEFINE_H_ */
