#ifndef _USER_DEFINE_H_
#define _USER_DEFINE_H_

/* DMA definition */
#define U4_RX_DMA_UNIT (CM_DMA1)
#define U2_RX_DMA_UNIT (CM_DMA1)

#define U4_RX_DMA_CH (DMA_CH0)
#define U2_RX_DMA_CH (DMA_CH1)

#define U4_RX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA1, ENABLE))
#define U2_RX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA1, ENABLE))

#define U4_RX_DMA_TRIG_SEL (AOS_DMA1_0)
#define U2_RX_DMA_TRIG_SEL (AOS_DMA1_1)

#define U4_RX_DMA_TRIG_EVT_SRC (EVT_SRC_USART4_RI)
#define U2_RX_DMA_TRIG_EVT_SRC (EVT_SRC_USART2_RI)

#define U4_RX_DMA_RECONF_TRIG_SEL (AOS_DMA_RC)
#define U2_RX_DMA_RECONF_TRIG_SEL (AOS_DMA_RC)

#define U4_RX_DMA_RECONF_TRIG_EVT_SRC (EVT_SRC_AOS_STRG)
#define U2_RX_DMA_RECONF_TRIG_EVT_SRC (EVT_SRC_AOS_STRG)

#define U4_RX_DMA_TC_INT (DMA_INT_TC_CH0)
#define U2_RX_DMA_TC_INT (DMA_INT_TC_CH1)

#define U4_RX_DMA_TC_FLAG (DMA_FLAG_TC_CH0)
#define U2_RX_DMA_TC_FLAG (DMA_FLAG_TC_CH1)

#define U4_RX_DMA_TC_IRQn (INT000_IRQn)
#define U2_RX_DMA_TC_IRQn (INT005_IRQn)

#define U4_RX_DMA_TC_INT_SRC (INT_SRC_DMA1_TC0)
#define U2_RX_DMA_TC_INT_SRC (INT_SRC_DMA1_TC1)

#define U4_TX_DMA_UNIT (CM_DMA2)
#define U2_TX_DMA_UNIT (CM_DMA2)

#define U4_TX_DMA_CH (DMA_CH0)
#define U2_TX_DMA_CH (DMA_CH1)

#define U4_TX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA2, ENABLE))
#define U2_TX_DMA_FCG_ENABLE() (FCG_Fcg0PeriphClockCmd(FCG0_PERIPH_DMA2, ENABLE))

#define U4_TX_DMA_TRIG_SEL (AOS_DMA2_0)
#define U2_TX_DMA_TRIG_SEL (AOS_DMA2_1)

#define U4_TX_DMA_TRIG_EVT_SRC (EVT_SRC_USART4_TI)
#define U2_TX_DMA_TRIG_EVT_SRC (EVT_SRC_USART2_TI)

#define U4_TX_DMA_TC_INT (DMA_INT_TC_CH0)
#define U2_TX_DMA_TC_INT (DMA_INT_TC_CH1)

#define U4_TX_DMA_TC_FLAG (DMA_FLAG_TC_CH0)
#define U2_TX_DMA_TC_FLAG (DMA_FLAG_TC_CH1)

#define U4_TX_DMA_TC_IRQn (INT001_IRQn)
#define U2_TX_DMA_TC_IRQn (INT006_IRQn)

#define U4_TX_DMA_TC_INT_SRC (INT_SRC_DMA2_TC0)
#define U2_TX_DMA_TC_INT_SRC (INT_SRC_DMA2_TC1)

/* Timer0 unit & channel definition */
#define U4_TMR0_UNIT (CM_TMR0_2)
// U2对应的是TMR0_1 CHB，U4对应的是TMR0_2 CHB，注意区分
#define U2_TMR0_UNIT (CM_TMR0_1)

#define U4_TMR0_CH (TMR0_CH_B)
#define U2_TMR0_CH (TMR0_CH_B)

#define U4_TMR0_FCG_ENABLE() (FCG_Fcg2PeriphClockCmd(FCG2_PERIPH_TMR0_2, ENABLE))
#define U2_TMR0_FCG_ENABLE() (FCG_Fcg2PeriphClockCmd(FCG2_PERIPH_TMR0_1, ENABLE))

/* USART RX/TX pin definition */
#define U4_USART_RX_PORT (GPIO_PORT_B) /* PB9: USART4_RX */
#define U2_USART_RX_PORT (GPIO_PORT_A) /* PA2: USART2_RX*/

#define U4_USART_RX_PIN (GPIO_PIN_09)
#define U2_USART_RX_PIN (GPIO_PIN_02)

#define U4_USART_RX_GPIO_FUNC (GPIO_FUNC_37)
#define U2_USART_RX_GPIO_FUNC (GPIO_FUNC_37)

#define U4_USART_TX_PORT (GPIO_PORT_B) /* PB8: USART4_TX */
#define U2_USART_TX_PORT (GPIO_PORT_A) /* PA3: USART2_TX */

#define U4_USART_TX_PIN (GPIO_PIN_08)
#define U2_USART_TX_PIN (GPIO_PIN_03)

#define U4_USART_TX_GPIO_FUNC (GPIO_FUNC_36)
#define U2_USART_TX_GPIO_FUNC (GPIO_FUNC_36)

/* USART unit definition */
#define U4_USART_UNIT (CM_USART4)
#define U2_USART_UNIT (CM_USART2)

#define U4_USART_FCG_ENABLE() (FCG_Fcg1PeriphClockCmd(FCG1_PERIPH_USART4, ENABLE))
#define U2_USART_FCG_ENABLE() (FCG_Fcg1PeriphClockCmd(FCG1_PERIPH_USART2, ENABLE))

/* USART baudrate definition */
#define U4_USART_BAUDRATE (115200UL)
#define U2_USART_BAUDRATE (921600UL)

/* USART timeout bits definition */
#define U4_USART_TIMEOUT_BITS (2000U)
#define U2_USART_TIMEOUT_BITS (2000U)

/* USART interrupt definition */
#define U4_USART_TX_CPLT_IRQn (INT002_IRQn)
#define U2_USART_TX_CPLT_IRQn (INT007_IRQn)

#define U4_USART_TX_CPLT_INT_SRC (INT_SRC_USART4_TCI)
#define U2_USART_TX_CPLT_INT_SRC (INT_SRC_USART2_TCI)

#define U4_USART_RX_ERR_IRQn (INT003_IRQn)
#define U2_USART_RX_ERR_IRQn (INT008_IRQn)

#define U4_USART_RX_ERR_INT_SRC (INT_SRC_USART4_EI)
#define U2_USART_RX_ERR_INT_SRC (INT_SRC_USART2_EI)

#define U4_USART_RX_TIMEOUT_IRQn (INT004_IRQn)
#define U2_USART_RX_TIMEOUT_IRQn (INT009_IRQn)

#define U4_USART_RX_TIMEOUT_INT_SRC (INT_SRC_USART4_RTO)
#define U2_USART_RX_TIMEOUT_INT_SRC (INT_SRC_USART2_RTO)

/* Application frame length max definition */
#define APP_FRAME_LEN_MAX (500U)

#endif /* _USER_DEFINE_H_ */