/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'template' 
 * Target:  'template_Release' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "HC32F460PETB.h"



#endif /* RTE_COMPONENTS_H */
